import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import type { CollectionItem } from './types';

const seed: CollectionItem[] = [
  {id:'1',category:'movies',title:'Dune: Part Two',creator:'Denis Villeneuve',genre:'Sci-Fi',year:2024,rating:9.2,status:'Completed',favorite:true,image:'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&w=700&q=80',notes:'Monumental scale and an incredible score.',dateAdded:'2026-07-18',detail:'166 min'},
  {id:'2',category:'games',title:'Cyber Odyssey',creator:'Nova Studios',genre:'RPG',year:2025,rating:8.8,status:'Playing',favorite:true,image:'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=700&q=80',notes:'A beautiful world to get lost in.',dateAdded:'2026-07-15',detail:'42 hours'},
  {id:'3',category:'books',title:'The Creative Act',creator:'Rick Rubin',genre:'Creativity',year:2023,rating:8.6,status:'Reading',favorite:false,image:'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=700&q=80',notes:'Quiet, useful observations about making things.',dateAdded:'2026-07-12',detail:'432 pages'},
  {id:'4',category:'music',title:'Midnights',creator:'Taylor Swift',genre:'Pop',year:2022,rating:8.4,status:'Completed',favorite:true,image:'https://images.unsplash.com/photo-1496293455970-f8581aae0e3b?auto=format&fit=crop&w=700&q=80',notes:'Perfect late-night record.',dateAdded:'2026-07-08',detail:'44 min'},
  {id:'5',category:'movies',title:'Past Lives',creator:'Celine Song',genre:'Drama',year:2023,rating:8.9,status:'Plan to Watch',favorite:false,image:'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=700&q=80',notes:'',dateAdded:'2026-06-24',detail:'106 min'},
  {id:'6',category:'games',title:'Night Circuit',creator:'Pixel North',genre:'Racing',year:2024,rating:7.9,status:'Backlog',favorite:false,image:'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=700&q=80',notes:'',dateAdded:'2026-06-11',detail:'0 hours'},
  {id:'7',category:'books',title:'Tomorrow, and Tomorrow',creator:'Gabrielle Zevin',genre:'Fiction',year:2022,rating:9.0,status:'Completed',favorite:true,image:'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=700&q=80',notes:'A moving story about friendship and games.',dateAdded:'2026-05-20',detail:'416 pages'},
  {id:'8',category:'music',title:'Awaken, My Love!',creator:'Childish Gambino',genre:'R&B',year:2016,rating:9.1,status:'Completed',favorite:true,image:'https://images.unsplash.com/photo-1461360228754-6e81c478b882?auto=format&fit=crop&w=700&q=80',notes:'Warm, wild, timeless.',dateAdded:'2026-04-02',detail:'49 min'}
];
interface State { items: CollectionItem[]; theme:'dark'|'light'; add:(i:CollectionItem)=>void; update:(i:CollectionItem)=>void; remove:(id:string)=>void; toggleFavorite:(id:string)=>void; setTheme:(t:'dark'|'light')=>void; replace:(i:CollectionItem[])=>void; clear:()=>void; }
export const useCollection = create<State>()(persist((set)=>({items:seed,theme:'dark',add:(i)=>set(s=>({items:[i,...s.items]})),update:(i)=>set(s=>({items:s.items.map(x=>x.id===i.id?i:x)})),remove:(id)=>set(s=>({items:s.items.filter(x=>x.id!==id)})),toggleFavorite:(id)=>set(s=>({items:s.items.map(x=>x.id===id?{...x,favorite:!x.favorite}:x)})),setTheme:(theme)=>set({theme}),replace:(items)=>set({items}),clear:()=>set({items:[]})}),{name:'mycollection-store'}));
